app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from core import views
from cart.api import UserAPI, ProductAPI, PaymentAPI, OrderAPI

from .router import router


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('home/', views.HomeView.as_view(), name='home'),
    path('contact/', views.ContactView.as_view(), name='contact'),
    path('cart/', include('cart.urls', namespace='cart')),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('apis/',include(router.urls), name='apis'),
    path('api/user', UserAPI.as_view(), name="api_create_user"),
    path('api/productos', ProductAPI.as_view(), name="api_productos"),
    path('api/payment', PaymentAPI.as_view(), name="api_payment"),
    path('api/order', OrderAPI.as_view(), name="api_order"),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.CartView.as_view(), name='summary'),
    path('shop/', views.ProductListView.as_view(), name='product-list'),
    path('shop/<slug>/', views.ProductDetailView.as_view(), name='product-detail'),
    path('increase-quantity/<pk>/', views.IncreaseQuantityView.as_view(), name='increase-quantity'),
    path('decrease-quantity/<pk>/', views.DecreaseQuantityView.as_view(), name='decrease-quantity'),
    path('remove-from-cart/<pk>/', views.RemoveFromCartView.as_view(), name='remove-from-cart'),
    path('checkout/', views.CheckoutView.as_view(), name='checkout'),
    path('payment/', views.PaymentView.as_view(), name='payment'),
    path('thank-you/', views.ThankYouView.as_view(), name='thank-you'),
    path('confirm-order/', views.ConfirmOrderView.as_view(), name='confirm-order'),
    path('orders/<pk>/', views.OrderDetailView.as_view(), name='order-detail'),
    
]

cart/forms.py
from django import forms
from .models import OrderItem, Product, Address, ColourVariation, SizeVariation
from django.contrib.auth import get_user_model

User = get_user_model()


class AddToCartForm(forms.ModelForm):
    colour = forms.ModelChoiceField(queryset=ColourVariation.objects.none())
    size = forms.ModelChoiceField(queryset=SizeVariation.objects.none())
    quantity = forms.IntegerField(min_value=1)

    class Meta:
        model = OrderItem
        fields = ['quantity', 'colour', 'size']

    def __init__(self, *args, **kwargs):
        self.product_id = kwargs.pop('product_id')
        product = Product.objects.get(id=self.product_id)
        super().__init__(*args, **kwargs)

        self.fields['colour'].queryset = product.available_colours.all()
        self.fields['size'].queryset = product.available_sizes.all()
 
    def clean(self):
        product_id = self.product_id
        product = Product.objects.get(id=self.product_id)
        quantity = self.cleaned_data['quantity']

        if product.stock < quantity:
            raise forms.ValidationError(
                f"The maximum stock is {product.stock}")


class AddressForm(forms.Form):

    shipping_address_line_1 = forms.CharField(required=False)
    shipping_address_line_2 = forms.CharField(required=False)
    shipping_zip_code = forms.CharField(required=False)
    shipping_city = forms.CharField(required=False)

    billing_address_line_1 = forms.CharField(required=False)
    billing_address_line_2 = forms.CharField(required=False)
    billing_zip_code = forms.CharField(required=False)
    billing_city = forms.CharField(required=False)

    selected_shipping_address = forms.ModelChoiceField(
        Address.objects.none(), required=False
    )

    selected_billing_address = forms.ModelChoiceField(
        Address.objects.none(), required=False
    )

    def __init__(self, *args, **kwargs):
        user_id = kwargs.pop('user_id')
        super().__init__(*args, **kwargs)

        user = User.objects.get(id=user_id)

        shipping_address_qs = Address.objects.filter(
            user=user,
            address_type='S'
        )

        billing_address_qs = Address.objects.filter(
            user=user,
            address_type='B'
        )

        self.fields['selected_shipping_address'].queryset = shipping_address_qs
        self.fields['selected_billing_address'].queryset = billing_address_qs

    def clean(self):
        data = self.cleaned_data

        selected_shipping_address = data.get('selected_shipping_address', None)
        if selected_shipping_address is None:
            if not data.get('shipping_address_line_1', None):
                self.add_error("shipping_address_line_1",
                               "Please fill in this field")
            if not data.get('shipping_address_line_2', None):
                self.add_error("shipping_address_line_2",
                               "Please fill in this field")
            if not data.get('shipping_zip_code', None):
                self.add_error("shipping_zip_code",
                               "Please fill in this field")
            if not data.get('shipping_city', None):
                self.add_error("shipping_city", "Please fill in this field")

        selected_billing_address = data.get('selected_billing_address', None)
        if selected_billing_address is None:
            if not data.get('billing_address_line_1', None):
                self.add_error("billing_address_line_1",
                               "Please fill in this field")
            if not data.get('billing_address_line_2', None):
                self.add_error("billing_address_line_2",
                               "Please fill in this field")
            if not data.get('billing_zip_code', None):
                self.add_error("billing_zip_code", "Please fill in this field")
            if not data.get('billing_city', None):
                self.add_error("billing_city", "Please fill in this field")

cart/views.py
from django.shortcuts import render
import datetime
import json
from django.db.models import Q
from django.views import generic
from .models import ColourVariation, Product, OrderItem, Address, Payment, Order, Category
from .utils import get_or_set_order_session
from django.shortcuts import get_object_or_404, reverse, redirect
from .forms import AddToCartForm, AddressForm
from django.contrib import messages, auth

#########
from rest_framework import viewsets
from .serializers import ColourVariationSerializer, OrderItemSerializer, OrderSerializer, PaymentSerializer, ProductSerializer

############
from django.conf import settings
from django.http import JsonResponse
from django.contrib.auth.mixins import LoginRequiredMixin



# Create your views here.
class ProductListView(generic.ListView):
    template_name='cart/product_list.html'
    #queryset = Product.objects.all()

    def get_queryset(self):
        qs = Product.objects.all()
        categoria = self.request.GET.get('categoria', None)
        if categoria:
            qs = qs.filter(Q(categoria__name=categoria))
        return qs

    def get_context_data(self, **kwargs):
        context = super(ProductListView, self).get_context_data(**kwargs)
        context.update({
            "categories": Category.objects.all()
        })
        return context

class ProductDetailView(generic.FormView):
    template_name = 'cart/product_detail.html'
    form_class = AddToCartForm

    def get_object(self):
        return get_object_or_404(Product, slug=self.kwargs["slug"])
    
    def get_success_url(self):
        return reverse("cart:summary")

    def get_form_kwargs(self):
        kwargs = super(ProductDetailView, self).get_form_kwargs()
        kwargs["product_id"] = self.get_object().id
        return kwargs

    def form_valid(self, form):
        order = get_or_set_order_session(self.request)
        product = self.get_object()

        item_filter = order.items.filter(
            product=product,
            colour=form.cleaned_data['colour'],
            size=form.cleaned_data['size'])

        if item_filter.exists():
            item = item_filter.first()
            item.quantity += int(form.cleaned_data['quantity'])
            item.save()

        else:
            new_item = form.save(commit=False)
            new_item.product = product
            new_item.order = order
            new_item.save()
        
        return super(ProductDetailView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(ProductDetailView, self).get_context_data(**kwargs)
        context['product'] = self.get_object()
        return context

class CartView(generic.TemplateView):
    template_name = 'cart/cart.html'

    def get_context_data(self,*args,**kwargs):
        context = super(CartView, self).get_context_data(**kwargs)
        context["order"] = get_or_set_order_session(self.request)
        return context

class IncreaseQuantityView(generic.View):
    def get(self, request, *args, **kwargs):
        order_item = get_object_or_404(OrderItem, id=kwargs['pk'])
        order_item.quantity += 1
        order_item.save()
        return redirect("cart:summary")

class DecreaseQuantityView(generic.View):
    def get(self, request, *args, **kwargs):
        order_item = get_object_or_404(OrderItem, id=kwargs['pk'])

        if order_item.quantity <= 1:
            order_item.delete()
        else:
            order_item.quantity -= 1
            order_item.save()
        return redirect("cart:summary")

class RemoveFromCartView(generic.View):
    def get(self, request, *args, **kwargs):
        order_item = get_object_or_404(OrderItem, id=kwargs['pk'])
        order_item.delete()
        return redirect("cart:summary")

class CheckoutView(generic.FormView):
    template_name = 'cart/checkout.html'
    form_class = AddressForm

    def get_success_url(self):
        return reverse("cart:payment")

    def form_valid(self, form):
        order = get_or_set_order_session(self.request)
        selected_shipping_address = form.cleaned_data.get('selected_shipping_address')
        selected_billing_address = form.cleaned_data.get('selected_billing_address')

        if selected_shipping_address:
            order.shipping_address = selected_shipping_address
        else:
            address = Address.objects.create(
                address_type = 'S',
                user = self.request.user,
                address_line_1=form.cleaned_data['shipping_address_line_1'],
                address_line_2=form.cleaned_data['shipping_address_line_2'],
                zip_code=form.cleaned_data['shipping_zip_code'],
                city=form.cleaned_data['shipping_city'],
            )
            order.shipping_address = address

        if selected_billing_address:
            order.billing_address = selected_billing_address
        else:
            address = Address.objects.create(
                address_type = 'B',
                user = self.request.user,
                address_line_1=form.cleaned_data['billing_address_line_1'],
                address_line_2=form.cleaned_data['billing_address_line_2'],
                zip_code=form.cleaned_data['billing_zip_code'],
                city=form.cleaned_data['billing_city'],
            )
            order.billing_address = address

        order.save()
        messages.info(
            self.request, "You have successfully added your addresses")
        return super(CheckoutView, self).form_valid(form)

    def get_form_kwargs(self):
        kwargs = super(CheckoutView, self).get_form_kwargs()
        kwargs["user_id"] = self.request.user.id
        return kwargs

    def get_context_data(self, **kwargs):
        context = super(CheckoutView, self).get_context_data(**kwargs)
        context['order'] = get_or_set_order_session(self.request)
        return context

    def get_form_kwargs(self):
        kwargs = super(CheckoutView, self).get_form_kwargs()
        kwargs["user_id"] = self.request.user.id
        return kwargs

    def get_context_data(self, **kwargs):
        context = super(CheckoutView, self).get_context_data(**kwargs)
        context['order'] = get_or_set_order_session(self.request)
        return context

class PaymentView(generic.TemplateView):
    template_name = 'cart/payment.html'

    def get_context_data(self, **kwargs):
        context = super(PaymentView, self).get_context_data(**kwargs)
        context["PAYPAL_SANDBOX_CLIENTE_ID"] = settings.PAYPAL_SANDBOX_CLIENTE_ID
        context['order'] = get_or_set_order_session(self.request)
        context['CALLBACK_URL']= self.request.build_absolute_uri(reverse("cart:thank-you"))
        return context

class ThankYouView(generic.TemplateView):
    template_engine = 'cart/thanks.html'

class ConfirmOrderView(generic.View):
    def post(self, request, *args, **kwargs):
        order = get_or_set_order_session(request)
        body = json.loads(request.body)
        payment = Payment.objects.create(
            order=order,
            successful=True,
            raw_response = json.dumps(body),
            amount = float(body["purchase_units"][0]["amount"]["value"]),
            payment_method='PayPal'
        )
        order.ordered = True
        order.ordered_date = datetime.date.today()
        order.save()
        return JsonResponse({"data": "Success"})

class OrderDetailView(LoginRequiredMixin, generic.DetailView):
    template_name = 'order.html'
    queryset = Order.objects.all()
    context_object_name = 'order'

templates/cart/cart.html
{% extends "base.html" %}

{% block content %}

<div class="bg-light py-3">
    <div class="container">
        <div class="row">
            <div class="col-md-12 mb-0">
                <a href="{% url 'home' %}">Home</a>
                <span class="mx-2 mb-0">/</span>
                <strong class="text-block">Cart</strong>
            </div>
        </div>
    </div>
</div>

<div class="site-section">
    <div class="container">
        <div class="row mb-5">

            <div class="col-md-12">
                <div class="site-blocks-table">
                    <table>
                        <thead>
                            <tr>
                                <th>Image</th>
                                <th>Product</th>
                                <th>Price</th>
                                <th>Quantity</th>
                                <th>Total</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for item in order.items.all %}
                            <tr>
                                <td class="product-thumbnail">
                                    <img src="{{ item.product.image.url }}" class="img-fluid">
                                </td>
                                <td class="product-name">
                                    <h2 class="h5 text-black">{{ item.product.nombre }}</h2>
                                    <small>Size: {{ item.size.name }}</small>
                                    <small>Colour: {{ item.colour.name }}</small>
                                </td>
                                <td>${{ item.product.get_price }}</td>
                                <td>
                                    <div class="input-group mb-3" style="max-width: 120px;">
                                        <div class="input-group-pretend">
                                            <a href="{% url 'cart:decrease-quantity' item.id %}"
                                                class="btn btn-outline-primary">
                                                &minus;
                                            </a>
                                        </div>
                                        <input type="text" class="form-control text-center" value="{{ item.quantity }}">
                                        <div class="input-group-append">
                                            <a href="{% url 'cart:increase-quantity' item.id %}"
                                                class="btn btn-outline-primary">
                                                &plus;
                                            </a>
                                        </div>
                                    </div>
                                </td>
                                <td>
                                    ${{ item.get_total_item_price }}
                                </td>
                                <td>
                                    <a href="{% url 'cart:remove-from-cart' item.id %}"
                                        class="btn btn-primary btn-sm">x</a>
                                </td>
                            </tr>
                            {% empty %}
                            <tr>
                                <td colspan="6">
                                    No tienes productos. <a href="{% url 'cart:product-list' %}">Continuar Comprando</a>

                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>

        </div>

        {% if order.items.count > 0 %}

        <div class="row">
            <div class="col-md-6">
                <div class="row mb-5">
                    <div class="col-md-12">
                        <a class="btn btn-outline-primary btn-sm btn-block"
                            href="{% url 'cart:product-list' %}">Continuar Comprando</a>
                    </div>
                </div>
            </div>

            <div class="col-md-6 pl-5">
                <div class="row justify-content-end">
                    <div class="col-md-12">
                        <div class="row">
                            <div class="col-md-12 text-right border-bottom mb-5">
                                <h3 class="text-black h4 text-uppercase">Cart Totals</h3>
                            </div>
                        </div>

                        <div class="row mb-3">
                            <div class="col-md-6">
                                <span class="text-black">SubTotal</span>
                            </div>
                            <div class="col-md-6">
                                <strong class="text-black">${{ order.get_subtotal }}</strong>
                            </div>


                        </div>

                        <div class="row mb-5">
                            <div class="col-md-6">
                                <span class="text-black">Total</span>
                            </div>
                            <div class="col-md-6">
                                <strong class="text-black">${{ order.get_total }}</strong>
                            </div>


                        </div>

                        <div class="row">
                            <div class="col-md-12">
                                <a href="{% url 'cart:checkout' %}" class="btn btn-warning btn-lg py-3 btn-block">Proceed to Checkout</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        {% endif %}

    </div>
</div>


{% endblock content %}

templates/cart/checkout.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block content %}

<div class="bg-light py-3">
    <div class="container">
        <div class="row">
            <div class="col-md-12 mb-0">
                <a href="{% url 'home' %}">Home</a>
                <span class="mx-2 mb-0">/</span>
                <a href="{% url 'cart:summary' %}">Cart</a>
                <span class="mx-2 mb-0">/</span>
                <strong class="text-block">Cart</strong>
            </div>
        </div>
    </div>
</div>

<div class="site-section">
    <div class="container">


        {% if not request.user.is_authenticated %}
        <div class="row mb-5">
            <div class="col-mb-12">
                <div class="border p-4 rounded" role="alert">
                    Casi has terminado con su pedido.
                    Para finalizar tu pedido, por favor <a href="">Login</a> or <a href="">Inscribir</a>

                </div>

                <div class="progress">
                    <div class="progress-bar" role="progressbar" style="width: 90%;" aria-label="90" aria-valuemin="0"
                        aria-valuemax="100">
                        90% Complete

                    </div>
                </div>
            </div>
        </div>
        {% else %}

        <form method="POST">
            {% csrf_token %}
            <div class="row">
                <div class="col-md-6 mb-mb-0">
                    <h2 class="h3 mb-3 text-black text-center">Billing Details</h2>
                    <hr />
                    <div class="p-2 p-lg-2">
                        {{form|crispy}}

                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-success btn-lg py-3 btn-block">
                            Proceder al pago.

                        </button>
                    </div>
                </div>

                <div class="col-md-6">
                    <div class="row mb-5">
                        <div class="col-md-12">
                            <h2 class="h3 mb-3 text-black text-center">Tu orden</h2>
                            <hr>
                            <div class="p-3 p-lg-5">
                                <table class="table site-block-order-table mb-5">
                                    <thead>
                                        <th>Product</th>
                                        <th>Total</th>
                                    </thead>
                                    <tbody>
                                        {% for item in order.items.all %}
                                        <tr>

                                            <td>
                                                {{item.size.name}}, {{item.colour.name}} {{ item.product.nombre }}
                                                <strong class="mx-2">x</strong> {{item.quantity}}

                                            </td>


                                            <td>
                                                ${{ item.get_total_item_price }}
                                            </td>

                                        </tr>

                                        {% endfor %}
                                        <tr>
                                            <td>
                                                <strong class="text-black font-weight-bold">SubTotal</strong>
                                            <td>${{order.get_subtotal}}</td>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <strong>Orden Total</strong>
                                            <td><strong
                                                    class="text-black font-weight-bold">${{order.get_total}}</strong>
                                            </td>
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>

                            </div>

                        </div>
                    </div>
                </div>

            </div>

        </form>

        {% endif %}


    </div>
</div>

{% endblock content %}

templates/cart/payment.html
{% extends "base.html" %}

{% block content %}

<style>
  .lds-ring {
    display: inline-block;
    position: relative;
    width: 80px;
    height: 80px;
  }

  .lds-ring div {
    box-sizing: border-box;
    display: block;
    position: absolute;
    width: 64px;
    height: 64px;
    margin: 8px;
    border: 8px solid rgb(155, 81, 81);
    border-radius: 50%;
    animation: lds-ring 1.2s cubic-bezier(0.5, 0, 0.5, 1) infinite;
    border-color: rgb(155, 81, 81) transparent transparent transparent;
  }

  .lds-ring div:nth-child(1) {
    animation-delay: -0.45s;
  }

  .lds-ring div:nth-child(2) {
    animation-delay: -0.3s;
  }

  .lds-ring div:nth-child(3) {
    animation-delay: -0.15s;
  }

  @keyframes lds-ring {
    0% {
      transform: rotate(0deg);
    }

    100% {
      transform: rotate(360deg);
    }
  }
</style>


<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">

      {% comment %} <div class="alert alert-success" role="alert" id="alertSuccess" style="display: none;">
        Your payment was successful.
      </div>

      <div class="alert alert-danger" role="alert" id="alertFailure" style="display: none;">
        Your payment failed. Please try again.
      </div>


      <div class="text-center py-3">
        <div id="loader" class="lds-ring" style="margin:auto; display:none;">
          <div></div>
          <div></div>
          <div></div>
          <div></div>
        </div>
      </div> {% endcomment %}

      
      <div id='paymentInfo'>
        <p>Order Total: ${{ order.get_total }}</p>
        <h4>Select a payment method</h4>
        <div id="paypal-button-container"></div>
      </div>

    </div>

  </div>
</div>


{% endblock content %}


{% block scripts %}
<script src="https://www.paypal.com/sdk/js?client-id={{ PAYPAL_SANDBOX_CLIENTE_ID }}"></script>

<script>

  const loader = document.getElementById('loader');
  const paymentInfo = document.getElementById('paymentInfo');

  function toggleLoader(on){
    loader.style.display = on === true ? "block" : "none";
    paymentInfo.style.display = on === true ? "none": "block";
  }

  function getCookie(name) {
    let cookieValue = null;
    if (document.cookie && document.cookie !== '') {
      const cookies = document.cookie.split(';');
      for (let i = 0; i < cookies.length; i++) {
        const cookie = cookies[i].trim();
        if (cookie.substring(0, name.length + 1) === (name + '=')) {
          cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
          break;
        }
      }
    }
    return cookieValue;
  }

  const csrftoken = getCookie('csrftoken');

  function sendOrderConfirmed() {
    return fetch("{url 'cart:confirm-order' %%}", {
      method: "post",
      body: JSON.stringify(details),
      headers: {
        "Content-Type": "application/json",
        "X-CSRFToken": csrftoken
      }
    })
  }

  paypal.Buttons({
    createOrder: function (data, actions) {
      return actions.order.create({
        purchase_units: [{
          amount: {
            value: '{{ order.get_total }}'
          }
        }]
      });
    },
    onApprove: function (data, actions) {
      toggleLoader(true);
      return actions.order.capture().then(function (details) {
        sendOrderConfirmed(details).then(res => {
          toggleLoader(false)
          const alertSuccess = document.getElementById('alertSuccess');
          alertSuccess.style.display = 'block';

          selfTimeout(function () {
            window.location.replace("{{CALLBACK_URL}}")
          }, 3000);
        })
      })
        .catch(err => {
          const alertFailure = document.getElementById('alertFailure');
          alertFailure.style.display = "block";
        })
        .finally(() => toggleLoader(false));
    }
  }).render('#paypal-button-container');
</script>
{% endblock scripts %}

templates/cart/product_detail.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}

<div class="bg-light py-3">
    <div class="container">
        <div class="row">
            <div class="col-md-12 mb-0">
                <a href="{% url 'home' %}">Home/a>
                    <span class="mx-2 mb-0">/</span>
                    <strong class="text-block">{{ product.nombre }}</strong>
            </div>
        </div>
    </div>
</div>

<div class="site-section">
    <div class="container">
        <div class="row mb-5">

            <div class="col-mb-6">
                <a><img src="{{ product.image.url }}" class="img-fluid"></a>
            </div>

            <div class="col-md-6 mb-4" data-aos='fade-up'>
                <h2 class="text-black">{{ product.nombre }}</h2>
                <p>{{ product.descripcion }}</p>

                <p>Available Stock: {{ product.stock }}</p>
                {% if product.in_stock %}

                <form method="POST">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button type='submit' class="btn btn-sm btn-primary buy-now">Add to Cart</button>
                </form>

                {% else %}
                <p>This item is out of stock</p>
                {% endif %}
            </div>

        </div>

    </div>
</div>


{% endblock content %}

templates/cart/product_list.html
{% extends "base.html" %}

{% block content %}

<div class="bg-light py-3">
    <div class="container">
        <div class="row">
            <div class="col-md-12 mb-0">
                <a href="{% url 'home' %}">Home</a>
                    <span class="mx-2 mb-0">/</span>
                    <strong class="text-block">Shop</strong>
            </div>
        </div>
    </div>
</div>


<div class="site-section">
    <div class="container">
        <div class="row mb-5">
            {% for product in object_list %}
            <div class="col-lg-4 col-md-6 mb-4" data-aos='fade-up'>

                <figure class="block-4-image">
                    <a href="{{ product.get_absolute_url }}" ><img src="{{ product.image.url }}" class="img-fluid"></a>
                </figure>
                <div class="block-4-text p-4">

                    <a href="{{ product.get_absolute_url }}"><h3>{{ product.nombre }}</h3></a>          
                    <p class="mb-0">{{product.descripcion}}</p>

                </div>
            </div>
            
            {% endfor %}

            <div class="col-md-3 mb-4">
                <div class="border p-4 rounded mb-4">
                    <h3 class="h6 text-uppercasse text-black">Categories</h3>
                    <ul>
                        {% for categoria in categories %}
                        <li class="mb-1">
                            <a href="?categoria={{ categoria.name }}" class="d-flex">
                                <span>{{ categoria.name }}</span>
                            </a>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>


        </div>

    </div>
</div>


{% endblock content %}

templates/cart/thanks.html
{% extends "base.html" %}

{% block content %}

<h2>Thanks</h2>

{% endblock content %}